import { useCallback, useEffect, useRef, useState } from "react";
import { Eye, Pencil, Plus, RotateCcw, Save, Settings2, Tag, Trash2, X } from "lucide-react";
import api from "../services/api";
import "./Unite.css";

const initialForm = { idMarque: "", numeroSerie: "", designation: "", modele: "", etalonnageRequis: "", periodiciteEtalonnage: "" };
const initialBrandForm = { nomMarque: "", nomFabricant: "" };

function Equipement() {
  const formRef = useRef(null);
  const [form, setForm] = useState(initialForm); const [brands, setBrands] = useState([]); const [equipment, setEquipment] = useState([]);
  const [errors, setErrors] = useState({}); const [message, setMessage] = useState(""); const [isSaving, setSaving] = useState(false); const [editingId, setEditingId] = useState(null);
  const [isListVisible, setListVisible] = useState(false); const [isLoading, setLoading] = useState(false);
  const [isBrandsVisible, setBrandsVisible] = useState(false); const [isBrandFormVisible, setBrandFormVisible] = useState(false); const [brandForm, setBrandForm] = useState(initialBrandForm); const [brandErrors, setBrandErrors] = useState({}); const [editingBrandId, setEditingBrandId] = useState(null); const [isSavingBrand, setSavingBrand] = useState(false);

  const loadBrands = useCallback(async () => { try { const { data } = await api.get("/api/marques"); setBrands(data); } catch { setBrandErrors({ form: "Impossible de charger les marques." }); } }, [setBrandErrors]);
  const loadEquipment = useCallback(async () => { try { setLoading(true); const { data } = await api.get("/api/equipements"); setEquipment(data); } catch { setErrors((current) => ({ ...current, form: "Impossible de charger les équipements." })); } finally { setLoading(false); } }, []);
  useEffect(() => { api.get("/api/marques").then(({ data }) => setBrands(data)).catch(() => setBrandErrors({ form: "Impossible de charger les marques." })); }, []);

  const handleChange = ({ target: { name, value } }) => { setForm((current) => ({ ...current, [name]: value })); setErrors((current) => ({ ...current, [name]: undefined, form: undefined })); setMessage(""); };
  const validate = () => { const next = {}; if (!form.idMarque) next.idMarque = "La marque est obligatoire."; if (!form.numeroSerie.trim()) next.numeroSerie = "Le numéro de série est obligatoire."; if (!form.designation.trim()) next.designation = "La désignation est obligatoire."; setErrors(next); return !Object.keys(next).length; };
  const handleSubmit = async (event) => { event.preventDefault(); setMessage(""); if (!validate()) return; try { setSaving(true); const payload = { ...form, idMarque: Number(form.idMarque), etalonnageRequis: form.etalonnageRequis === "" ? null : form.etalonnageRequis === "true", ...(editingId ? {} : { statut: "Actif" }) }; if (editingId) await api.put(`/api/equipements/${editingId}`, payload); else await api.post("/api/equipements", payload); const wasEditing = Boolean(editingId); setForm(initialForm); setEditingId(null); setMessage(wasEditing ? "L’équipement a été modifié avec succès." : "L’équipement a été enregistré avec succès."); if (isListVisible) loadEquipment(); } catch (error) { const response = error.response?.data; setErrors(response?.messages || { form: response?.message || "L’enregistrement a échoué." }); } finally { setSaving(false); } };
  const resetForm = () => { setForm(initialForm); setEditingId(null); setErrors({}); setMessage(""); };
  const editEquipment = (item) => { setForm({ idMarque: String(item.idMarque), numeroSerie: item.numeroSerie || "", designation: item.designation || "", modele: item.modele || "", etalonnageRequis: item.etalonnageRequis == null ? "" : String(item.etalonnageRequis), periodiciteEtalonnage: item.periodiciteEtalonnage || "" }); setEditingId(item.idEquipement); setErrors({}); setMessage(""); formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const deleteEquipment = async (item) => { if (!window.confirm(`Désactiver l’équipement « ${item.designation} » ? Il ne sera plus affiché dans la liste.`)) return; try { await api.put(`/api/equipements/${item.idEquipement}`, { idMarque: item.idMarque, numeroSerie: item.numeroSerie, designation: item.designation, modele: item.modele, etalonnageRequis: item.etalonnageRequis, periodiciteEtalonnage: item.periodiciteEtalonnage, statut: "Inactif" }); if (editingId === item.idEquipement) resetForm(); setMessage("L’équipement a été désactivé."); loadEquipment(); } catch (error) { setErrors({ form: error.response?.data?.message || "La désactivation a échoué." }); } };
  const toggleList = () => { const next = !isListVisible; setListVisible(next); if (next) loadEquipment(); };

  const resetBrandForm = () => { setBrandForm(initialBrandForm); setEditingBrandId(null); setBrandErrors({}); setBrandFormVisible(false); };
  const saveBrand = async (event) => { event.preventDefault(); const next = {}; if (!brandForm.nomMarque.trim()) next.nomMarque = "Le nom de la marque est obligatoire."; if (Object.keys(next).length) { setBrandErrors(next); return; } try { setSavingBrand(true); if (editingBrandId) await api.put(`/api/marques/${editingBrandId}`, brandForm); else await api.post("/api/marques", brandForm); resetBrandForm(); loadBrands(); } catch (error) { const response = error.response?.data; setBrandErrors(response?.messages || { form: response?.message || "L’enregistrement de la marque a échoué." }); } finally { setSavingBrand(false); } };
  const editBrand = (brand) => { setBrandForm({ nomMarque: brand.nomMarque, nomFabricant: brand.nomFabricant || "" }); setEditingBrandId(brand.idMarque); setBrandFormVisible(true); setBrandErrors({}); };
  const deleteBrand = async (brand) => { if (!window.confirm(`Supprimer la marque « ${brand.nomMarque} » ? Cette action est irréversible.`)) return; try { await api.delete(`/api/marques/${brand.idMarque}`); if (editingBrandId === brand.idMarque) resetBrandForm(); loadBrands(); } catch (error) { setBrandErrors({ form: error.response?.data?.message || "La suppression de la marque a échoué." }); } };
  const brandName = (id) => brands.find((brand) => brand.idMarque === id)?.nomMarque || "—";
  const fieldError = (name) => errors[name] && <span className="field-error">{errors[name]}</span>;

  return <section className="unite-page"><div className="page-heading"><div><p className="dashboard-eyebrow">Référentiel</p><h1>Gestion des équipements</h1><p>Créez et organisez les équipements du référentiel LPEE.</p></div><span className="page-heading-icon"><Settings2 /></span></div>
    <div className="unit-toolbar"><button className="region-button" onClick={() => { const next = !isBrandsVisible; setBrandsVisible(next); if (next) loadBrands(); }}><Tag size={18} />Marque</button><button className="view-units-button" onClick={toggleList}><Eye size={18} />{isListVisible ? "Masquer les équipements" : "Voir les équipements"}</button></div>
    <article className="unite-form-card" ref={formRef}><div className="form-card-heading"><div><h2>{editingId ? "Modifier l’équipement" : "Nouvel équipement"}</h2><p>Les champs marqués d’un astérisque sont obligatoires.</p></div>{editingId && <button className="cancel-edit-button" onClick={resetForm}><X size={17} />Annuler la modification</button>}</div><form className="unite-form" onSubmit={handleSubmit} noValidate><div className="form-grid">
      <div className="form-field"><label htmlFor="idMarque">Marque <b>*</b></label><select id="idMarque" name="idMarque" value={form.idMarque} onChange={handleChange} aria-invalid={Boolean(errors.idMarque)}><option value="">Sélectionnez une marque</option>{brands.map((brand) => <option key={brand.idMarque} value={brand.idMarque}>{brand.nomMarque}</option>)}</select>{fieldError("idMarque")}</div><div className="form-field"><label htmlFor="numeroSerie">Numéro de série <b>*</b></label><input id="numeroSerie" name="numeroSerie" value={form.numeroSerie} onChange={handleChange} aria-invalid={Boolean(errors.numeroSerie)} />{fieldError("numeroSerie")}</div>
      <div className="form-field"><label htmlFor="designation">Désignation <b>*</b></label><input id="designation" name="designation" value={form.designation} onChange={handleChange} aria-invalid={Boolean(errors.designation)} />{fieldError("designation")}</div><div className="form-field"><label htmlFor="modele">Modèle</label><input id="modele" name="modele" value={form.modele} onChange={handleChange} /></div>
      <div className="form-field"><label htmlFor="etalonnageRequis">Étalonnage requis</label><select id="etalonnageRequis" name="etalonnageRequis" value={form.etalonnageRequis} onChange={handleChange}><option value="">Non renseigné</option><option value="true">Oui</option><option value="false">Non</option></select></div><div className="form-field"><label htmlFor="periodiciteEtalonnage">Périodicité d’étalonnage</label><input id="periodiciteEtalonnage" name="periodiciteEtalonnage" value={form.periodiciteEtalonnage} onChange={handleChange} placeholder="Ex. Annuelle" /></div>
    </div>{errors.form && <p className="form-global-error" role="alert">{errors.form}</p>}{message && <p className="form-success" role="status">{message}</p>}<div className="form-actions"><button type="button" className="reset-button" onClick={resetForm}><RotateCcw size={18} />Réinitialiser</button><button className="save-button" type="submit" disabled={isSaving}><Save size={18} />{isSaving ? "Enregistrement…" : editingId ? "Modifier" : "Enregistrer"}</button></div></form></article>
    {isListVisible && <article className="units-list-card"><div className="list-card-heading"><div><h2>Liste des équipements</h2><p>{isLoading ? "Chargement…" : `${equipment.filter((item) => item.statut?.trim().toLowerCase() !== "inactif").length} équipement(s) disponible(s)`}</p></div></div><div className="units-table-wrap"><table><thead><tr><th>N° série</th><th>Désignation</th><th>Marque</th><th>Modèle</th><th>Actions</th></tr></thead><tbody>{isLoading ? <tr><td colSpan="6" className="table-state">Chargement des équipements…</td></tr> : equipment.filter((item) => item.statut?.trim().toLowerCase() !== "inactif").length ? equipment.filter((item) => item.statut?.trim().toLowerCase() !== "inactif").map((item) => <tr key={item.idEquipement}><td>{item.numeroSerie}</td><td><strong>{item.designation}</strong></td><td>{brandName(item.idMarque)}</td><td>{item.modele || "—"}</td><td><div className="table-actions"><button className="edit-action" onClick={() => editEquipment(item)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => deleteEquipment(item)}><Trash2 size={16} />Supprimer</button></div></td></tr>) : <tr><td colSpan="6" className="table-state">Aucun équipement disponible.</td></tr>}</tbody></table></div></article>}
    {isBrandsVisible && <article className="regions-card"><div className="list-card-heading"><div><h2>Gestion des marques</h2><p>{brands.length} marque(s) disponible(s)</p></div><button className="add-region-button" onClick={() => { resetBrandForm(); setBrandFormVisible(true); }}><Plus size={17} />Ajouter</button></div>{isBrandFormVisible && <form className="region-form" onSubmit={saveBrand} noValidate><div className="form-field"><label htmlFor="nomMarque">Nom de la marque <b>*</b></label><input id="nomMarque" name="nomMarque" value={brandForm.nomMarque} onChange={({ target }) => { setBrandForm((current) => ({ ...current, nomMarque: target.value })); setBrandErrors({}); }} aria-invalid={Boolean(brandErrors.nomMarque)} />{brandErrors.nomMarque && <span className="field-error">{brandErrors.nomMarque}</span>}</div><div className="form-field"><label htmlFor="nomFabricant">Nom du fabricant</label><input id="nomFabricant" name="nomFabricant" value={brandForm.nomFabricant} onChange={({ target }) => setBrandForm((current) => ({ ...current, nomFabricant: target.value }))} /></div><div className="region-form-actions"><button type="button" className="reset-button" onClick={resetBrandForm}>Annuler</button><button type="submit" className="save-button" disabled={isSavingBrand}>{isSavingBrand ? "Enregistrement…" : editingBrandId ? "Modifier" : "Ajouter"}</button></div></form>}{brandErrors.form && <p className="region-error" role="alert">{brandErrors.form}</p>}<div className="units-table-wrap"><table><thead><tr><th>Marque</th><th>Fabricant</th><th>Actions</th></tr></thead><tbody>{brands.length ? brands.map((brand) => <tr key={brand.idMarque}><td><strong>{brand.nomMarque}</strong></td><td>{brand.nomFabricant || "—"}</td><td><div className="table-actions"><button className="edit-action" onClick={() => editBrand(brand)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => deleteBrand(brand)}><Trash2 size={16} />Supprimer</button></div></td></tr>) : <tr><td colSpan="3" className="table-state">Aucune marque disponible.</td></tr>}</tbody></table></div></article>}
  </section>;
}

export default Equipement;
