import { useCallback, useEffect, useRef, useState } from "react";
import { Beaker, Eye, Pencil, Plus, RotateCcw, Save, Settings2, Trash2, X } from "lucide-react";
import api from "../services/api";
import "./Unite.css";

const initialForm = { idProduit: "", numeroEssai: "", description: "", dateEssai: "", etalonnage: "", parameterIds: [] };
const initialParameterForm = { nomParametre: "", uniteParametre: "" };

function Essai() {
  const formRef = useRef(null); const [form, setForm] = useState(initialForm); const [produits, setProduits] = useState([]); const [parametres, setParametres] = useState([]); const [essais, setEssais] = useState([]); const [associations, setAssociations] = useState([]); const [errors, setErrors] = useState({}); const [message, setMessage] = useState(""); const [editingId, setEditingId] = useState(null); const [saving, setSaving] = useState(false); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false); const [showParameters, setShowParameters] = useState(false); const [showParameterForm, setShowParameterForm] = useState(false); const [parameterForm, setParameterForm] = useState(initialParameterForm); const [parameterErrors, setParameterErrors] = useState({}); const [editingParameterId, setEditingParameterId] = useState(null);
  const loadEssais = useCallback(async () => { try { setLoading(true); const [essaiResponse, associationResponse] = await Promise.all([api.get("/api/essais"), api.get("/api/essais-parametres")]); setEssais(essaiResponse.data); setAssociations(associationResponse.data); } catch { setErrors((current) => ({ ...current, form: "Impossible de charger les essais." })); } finally { setLoading(false); } }, []);
  useEffect(() => { Promise.all([api.get("/api/produits"), api.get("/api/parametres")]).then(([p, pa]) => { setProduits(p.data); setParametres(pa.data); }).catch(() => setErrors({ form: "Impossible de charger les produits ou paramètres." })); }, []);
  const change = ({ target: { name, value } }) => { setForm((c) => ({ ...c, [name]: value })); setErrors((c) => ({ ...c, [name]: undefined, form: undefined })); setMessage(""); };
  const changeParameters = (event) => setForm((c) => ({ ...c, parameterIds: Array.from(event.target.selectedOptions, (option) => Number(option.value)) }));
  const validate = () => { const next = {}; if (!form.idProduit) next.idProduit = "Le produit est obligatoire."; if (!form.numeroEssai.trim()) next.numeroEssai = "Le numéro d’essai est obligatoire."; setErrors(next); return !Object.keys(next).length; };
  const syncParameters = async (idEssai, selectedIds) => { const { data: current } = await api.get(`/api/essais-parametres/essai/${idEssai}`); const currentIds = current.map((item) => item.idParametre); await Promise.all(current.filter((item) => !selectedIds.includes(item.idParametre)).map((item) => api.delete(`/api/essais-parametres/${item.idMesure}`))); await Promise.all(selectedIds.filter((id) => !currentIds.includes(id)).map((idParametre) => api.post("/api/essais-parametres", { idEssai, idParametre, statut: "Actif" })));
  };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; try { setSaving(true); const payload = { idProduit: Number(form.idProduit), numeroEssai: form.numeroEssai, description: form.description, dateEssai: form.dateEssai || null, etalonnage: form.etalonnage === "" ? null : form.etalonnage === "true", ...(editingId ? {} : { statut: "ACTIF" }) }; const response = editingId ? await api.put(`/api/essais/${editingId}`, payload) : await api.post("/api/essais", payload); const idEssai = editingId || response.data.idEssai; await syncParameters(idEssai, form.parameterIds); const edited = Boolean(editingId); setForm(initialForm); setEditingId(null); setMessage(edited ? "L’essai a été modifié avec succès." : "L’essai a été enregistré avec succès."); if (visible) loadEssais(); } catch (error) { const r = error.response?.data; setErrors(r?.messages || { form: r?.message || "L’enregistrement a échoué." }); } finally { setSaving(false); } };
  const reset = () => { setForm(initialForm); setEditingId(null); setErrors({}); setMessage(""); };
  const edit = (item) => { const selected = associations.filter((link) => link.idEssai === item.idEssai).map((link) => link.idParametre); setForm({ idProduit: String(item.idProduit), numeroEssai: item.numeroEssai || "", description: item.description || "", dateEssai: item.dateEssai || "", etalonnage: item.etalonnage == null ? "" : String(item.etalonnage), parameterIds: selected }); setEditingId(item.idEssai); setErrors({}); setMessage(""); formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const remove = async (item) => { if (!window.confirm(`Désactiver l’essai « ${item.numeroEssai} » ? Il ne sera plus affiché.`)) return; try { await api.put(`/api/essais/${item.idEssai}`, { idProduit: item.idProduit, numeroEssai: item.numeroEssai, description: item.description, dateEssai: item.dateEssai, etalonnage: item.etalonnage, statut: "INACTIF" }); if (editingId === item.idEssai) reset(); setMessage("L’essai a été désactivé."); loadEssais(); } catch (error) { setErrors({ form: error.response?.data?.message || "La désactivation a échoué." }); } };
  const loadParameters = async () => { try { const { data } = await api.get("/api/parametres"); setParametres(data); } catch { setParameterErrors({ form: "Impossible de charger les paramètres." }); } };
  const resetParameter = () => { setParameterForm(initialParameterForm); setEditingParameterId(null); setParameterErrors({}); setShowParameterForm(false); };
  const saveParameter = async (event) => { event.preventDefault(); if (!parameterForm.nomParametre.trim()) { setParameterErrors({ nomParametre: "Le nom du paramètre est obligatoire." }); return; } try { if (editingParameterId) await api.put(`/api/parametres/${editingParameterId}`, parameterForm); else await api.post("/api/parametres", parameterForm); resetParameter(); loadParameters(); } catch (error) { setParameterErrors(error.response?.data?.messages || { form: error.response?.data?.message || "L’enregistrement a échoué." }); } };
  const editParameter = (item) => { setParameterForm({ nomParametre: item.nomParametre, uniteParametre: item.uniteParametre || "" }); setEditingParameterId(item.idParametre); setShowParameterForm(true); };
  const deleteParameter = async (item) => { if (!window.confirm(`Supprimer le paramètre « ${item.nomParametre} » ?`)) return; try { await api.delete(`/api/parametres/${item.idParametre}`); loadParameters(); } catch (error) { setParameterErrors({ form: error.response?.data?.message || "La suppression a échoué." }); } };
  const productName = (id) => produits.find((p) => p.idProduit === id)?.nomProduit || "—"; const parametersFor = (id) => associations.filter((link) => link.idEssai === id).map((link) => parametres.find((p) => p.idParametre === link.idParametre)?.nomParametre).filter(Boolean);
  const field = (name) => errors[name] && <span className="field-error">{errors[name]}</span>; const activeEssais = essais.filter((item) => item.statut?.trim().toLowerCase() !== "inactif");
  return <section className="unite-page"><div className="page-heading"><div><p className="dashboard-eyebrow">Référentiel</p><h1>Gestion des essais</h1><p>Créez et organisez les essais de laboratoire.</p></div><span className="page-heading-icon"><Beaker /></span></div><div className="unit-toolbar"><button className="region-button" onClick={() => { const next = !showParameters; setShowParameters(next); if (next) loadParameters(); }}><Settings2 size={18} />Paramètres</button><button className="view-units-button" onClick={() => { const next = !visible; setVisible(next); if (next) loadEssais(); }}><Eye size={18} />{visible ? "Masquer les essais" : "Voir les essais"}</button></div>
    <article className="unite-form-card" ref={formRef}><div className="form-card-heading"><div><h2>{editingId ? "Modifier l’essai" : "Nouvel essai"}</h2><p>Les paramètres associés sont facultatifs.</p></div>{editingId && <button className="cancel-edit-button" onClick={reset}><X size={17} />Annuler la modification</button>}</div><form className="unite-form" onSubmit={submit} noValidate><div className="form-grid"><div className="form-field"><label htmlFor="idProduit">Produit <b>*</b></label><select id="idProduit" name="idProduit" value={form.idProduit} onChange={change} aria-invalid={Boolean(errors.idProduit)}><option value="">Sélectionnez un produit</option>{produits.map((p) => <option key={p.idProduit} value={p.idProduit}>{p.nomProduit} ({p.codeProduit})</option>)}</select>{field("idProduit")}</div><div className="form-field"><label htmlFor="numeroEssai">Numéro d’essai <b>*</b></label><input id="numeroEssai" name="numeroEssai" value={form.numeroEssai} onChange={change} aria-invalid={Boolean(errors.numeroEssai)} />{field("numeroEssai")}</div><div className="form-field"><label htmlFor="dateEssai">Date d’essai</label><input id="dateEssai" name="dateEssai" type="date" value={form.dateEssai} onChange={change} /></div><div className="form-field"><label htmlFor="etalonnage">Étalonnage</label><select id="etalonnage" name="etalonnage" value={form.etalonnage} onChange={change}><option value="">Non renseigné</option><option value="true">Oui</option><option value="false">Non</option></select></div><div className="form-field form-field-wide"><label htmlFor="description">Description</label><input id="description" name="description" value={form.description} onChange={change} /></div><div className="form-field form-field-wide"><label htmlFor="parameters">Paramètres associés</label><select id="parameters" multiple value={form.parameterIds.map(String)} onChange={changeParameters} className="parameters-select">{parametres.map((p) => <option key={p.idParametre} value={p.idParametre}>{p.nomParametre}{p.uniteParametre ? ` (${p.uniteParametre})` : ""}</option>)}</select><small className="field-help">Maintenez Ctrl/Cmd pour sélectionner plusieurs paramètres. Aucun choix est autorisé.</small></div></div>{errors.form && <p className="form-global-error" role="alert">{errors.form}</p>}{message && <p className="form-success" role="status">{message}</p>}<div className="form-actions"><button type="button" className="reset-button" onClick={reset}><RotateCcw size={18} />Réinitialiser</button><button className="save-button" type="submit" disabled={saving}><Save size={18} />{saving ? "Enregistrement…" : editingId ? "Modifier" : "Enregistrer"}</button></div></form></article>
    {visible && <article className="units-list-card"><div className="list-card-heading"><div><h2>Liste des essais</h2><p>{loading ? "Chargement…" : `${activeEssais.length} essai(s) disponible(s)`}</p></div></div><div className="units-table-wrap"><table><thead><tr><th>Numéro</th><th>Produit</th><th>Date</th><th>Paramètres associés</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="table-state">Chargement des essais…</td></tr> : activeEssais.length ? activeEssais.map((item) => <tr key={item.idEssai}><td><strong>{item.numeroEssai}</strong></td><td>{productName(item.idProduit)}</td><td>{item.dateEssai || "—"}</td><td>{parametersFor(item.idEssai).length ? parametersFor(item.idEssai).join(", ") : "—"}</td><td><div className="table-actions"><button className="edit-action" onClick={() => edit(item)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => remove(item)}><Trash2 size={16} />Supprimer</button></div></td></tr>) : <tr><td colSpan="5" className="table-state">Aucun essai disponible.</td></tr>}</tbody></table></div></article>}
    {showParameters && <article className="regions-card"><div className="list-card-heading"><div><h2>Gestion des paramètres</h2><p>{parametres.length} paramètre(s) disponible(s)</p></div><button className="add-region-button" onClick={() => { resetParameter(); setShowParameterForm(true); }}><Plus size={17} />Ajouter</button></div>{showParameterForm && <form className="region-form" onSubmit={saveParameter}><div className="form-field"><label>Nom du paramètre <b>*</b></label><input value={parameterForm.nomParametre} onChange={(e) => setParameterForm((c) => ({ ...c, nomParametre: e.target.value }))} />{parameterErrors.nomParametre && <span className="field-error">{parameterErrors.nomParametre}</span>}</div><div className="form-field"><label>Unité</label><input value={parameterForm.uniteParametre} onChange={(e) => setParameterForm((c) => ({ ...c, uniteParametre: e.target.value }))} /></div><div className="region-form-actions"><button type="button" className="reset-button" onClick={resetParameter}>Annuler</button><button className="save-button">{editingParameterId ? "Modifier" : "Ajouter"}</button></div></form>}{parameterErrors.form && <p className="region-error">{parameterErrors.form}</p>}<div className="units-table-wrap"><table><thead><tr><th>Paramètre</th><th>Unité</th><th>Actions</th></tr></thead><tbody>{parametres.map((item) => <tr key={item.idParametre}><td><strong>{item.nomParametre}</strong></td><td>{item.uniteParametre || "—"}</td><td><div className="table-actions"><button className="edit-action" onClick={() => editParameter(item)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => deleteParameter(item)}><Trash2 size={16} />Supprimer</button></div></td></tr>)}</tbody></table></div></article>}
  </section>;
}
export default Essai;
