import { useCallback, useEffect, useRef, useState } from "react";
import { Award, Building, Eye, Pencil, Plus, RotateCcw, Save, Trash2, X } from "lucide-react";
import api from "../services/api";
import "./Unite.css";

const initialForm = { idOrganisme: "", numeroNorme: "", codeNorme: "", nomNorme: "", annee: "" };
const initialOrganisme = { codeOrganisme: "", nomOrganisme: "", imageOrganisme: "" };
const isInactive = (item) => item.statut?.trim().toLowerCase() === "inactif";

function OrganismeImage({ src, alt }) {
  const [hasError, setHasError] = useState(false);
  if (!src || hasError) return <span className="organisme-image-fallback" title="Image indisponible"><Building size={19} /></span>;
  return <img className="organisme-image" src={src} alt={alt} onError={() => setHasError(true)} />;
}

function Norme() {
  const formRef = useRef(null); const [form, setForm] = useState(initialForm); const [normes, setNormes] = useState([]); const [errors, setErrors] = useState({}); const [message, setMessage] = useState(""); const [isSaving, setSaving] = useState(false); const [editingId, setEditingId] = useState(null); const [visible, setVisible] = useState(false); const [loading, setLoading] = useState(false);
  const [organismes, setOrganismes] = useState([]); const [showOrgs, setShowOrgs] = useState(false); const [showOrgForm, setShowOrgForm] = useState(false); const [orgForm, setOrgForm] = useState(initialOrganisme); const [orgErrors, setOrgErrors] = useState({}); const [editingOrgId, setEditingOrgId] = useState(null); const [savingOrg, setSavingOrg] = useState(false);
  const loadNormes = useCallback(async () => { try { setLoading(true); const { data } = await api.get("/api/normes"); setNormes(data); } catch { setErrors((current) => ({ ...current, form: "Impossible de charger les normes." })); } finally { setLoading(false); } }, []);
  const loadOrganismes = useCallback(async () => { try { const { data } = await api.get("/api/organismes"); setOrganismes(data); } catch { setOrgErrors({ form: "Impossible de charger les organismes." }); } }, [setOrgErrors]);
  useEffect(() => { api.get("/api/organismes").then(({ data }) => setOrganismes(data)).catch(() => setOrgErrors({ form: "Impossible de charger les organismes." })); }, []);
  const change = ({ target: { name, value } }) => { setForm((c) => ({ ...c, [name]: value })); setErrors((c) => ({ ...c, [name]: undefined, form: undefined })); setMessage(""); };
  const submit = async (event) => { event.preventDefault(); const next = {}; if (!form.idOrganisme) next.idOrganisme = "L’organisme est obligatoire."; if (!form.numeroNorme.trim()) next.numeroNorme = "Le numéro de norme est obligatoire."; if (!form.codeNorme.trim()) next.codeNorme = "Le code norme est obligatoire."; if (!form.nomNorme.trim()) next.nomNorme = "Le nom de la norme est obligatoire."; if (form.annee && (!Number.isInteger(Number(form.annee)) || Number(form.annee) < 0)) next.annee = "Saisissez une année valide."; if (Object.keys(next).length) { setErrors(next); return; } try { setSaving(true); const payload = { ...form, idOrganisme: Number(form.idOrganisme), annee: form.annee === "" ? null : Number(form.annee), ...(editingId ? {} : { statut: "Actif" }) }; if (editingId) await api.put(`/api/normes/${editingId}`, payload); else await api.post("/api/normes", payload); const edited = Boolean(editingId); setForm(initialForm); setEditingId(null); setMessage(edited ? "La norme a été modifiée avec succès." : "La norme a été enregistrée avec succès."); if (visible) loadNormes(); } catch (error) { const r = error.response?.data; setErrors(r?.messages || { form: r?.message || "L’enregistrement a échoué." }); } finally { setSaving(false); } };
  const reset = () => { setForm(initialForm); setEditingId(null); setErrors({}); setMessage(""); };
  const edit = (item) => { setForm({ idOrganisme: String(item.idOrganisme ?? ""), numeroNorme: item.numeroNorme || "", codeNorme: item.codeNorme || "", nomNorme: item.nomNorme || "", annee: item.annee ?? "" }); setEditingId(item.idNorme); setErrors({}); setMessage(""); formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const deactivate = async (item) => { if (!window.confirm(`Désactiver la norme « ${item.nomNorme} » ? Elle ne sera plus affichée.`)) return; try { await api.put(`/api/normes/${item.idNorme}`, { idOrganisme: item.idOrganisme, numeroNorme: item.numeroNorme, codeNorme: item.codeNorme, nomNorme: item.nomNorme, annee: item.annee, statut: "Inactif" }); if (editingId === item.idNorme) reset(); setMessage("La norme a été désactivée."); loadNormes(); } catch (error) { setErrors({ form: error.response?.data?.message || "La désactivation a échoué." }); } };
  const resetOrg = () => { setOrgForm(initialOrganisme); setEditingOrgId(null); setOrgErrors({}); setShowOrgForm(false); };
  const saveOrg = async (event) => { event.preventDefault(); const next = {}; if (!orgForm.codeOrganisme.trim()) next.codeOrganisme = "Le code organisme est obligatoire."; if (!orgForm.nomOrganisme.trim()) next.nomOrganisme = "Le nom de l’organisme est obligatoire."; if (Object.keys(next).length) { setOrgErrors(next); return; } try { setSavingOrg(true); if (editingOrgId) await api.put(`/api/organismes/${editingOrgId}`, orgForm); else await api.post("/api/organismes", orgForm); resetOrg(); loadOrganismes(); } catch (error) { const r = error.response?.data; setOrgErrors(r?.messages || { form: r?.message || "L’enregistrement de l’organisme a échoué." }); } finally { setSavingOrg(false); } };
  const editOrg = (item) => { setOrgForm({ codeOrganisme: item.codeOrganisme, nomOrganisme: item.nomOrganisme, imageOrganisme: item.imageOrganisme || "" }); setEditingOrgId(item.idOrganisme); setShowOrgForm(true); setOrgErrors({}); };
  const deleteOrg = async (item) => { if (!window.confirm(`Supprimer l’organisme « ${item.nomOrganisme} » ? Cette action est irréversible.`)) return; try { await api.delete(`/api/organismes/${item.idOrganisme}`); if (editingOrgId === item.idOrganisme) resetOrg(); loadOrganismes(); } catch (error) { setOrgErrors({ form: error.response?.data?.message || "La suppression a échoué." }); } };
  const field = (name) => errors[name] && <span className="field-error">{errors[name]}</span>; const activeNormes = normes.filter((item) => !isInactive(item)); const organismeName = (id) => organismes.find((item) => item.idOrganisme === id)?.nomOrganisme || "—";

  return <section className="unite-page"><div className="page-heading"><div><p className="dashboard-eyebrow">Référentiel</p><h1>Gestion des normes</h1><p>Créez et organisez les normes du référentiel LPEE.</p></div><span className="page-heading-icon"><Award /></span></div><div className="unit-toolbar"><button className="region-button" onClick={() => { const next = !showOrgs; setShowOrgs(next); if (next) loadOrganismes(); }}><Building size={18} />Organisme</button><button className="view-units-button" onClick={() => { const next = !visible; setVisible(next); if (next) loadNormes(); }}><Eye size={18} />{visible ? "Masquer les normes" : "Voir les normes"}</button></div>
    <article className="unite-form-card" ref={formRef}><div className="form-card-heading"><div><h2>{editingId ? "Modifier la norme" : "Nouvelle norme"}</h2><p>Les champs marqués d’un astérisque sont obligatoires.</p></div>{editingId && <button className="cancel-edit-button" onClick={reset}><X size={17} />Annuler la modification</button>}</div><form className="unite-form" onSubmit={submit} noValidate><div className="form-grid"><div className="form-field"><label htmlFor="idOrganisme">Organisme <b>*</b></label><select id="idOrganisme" name="idOrganisme" value={form.idOrganisme} onChange={change} aria-invalid={Boolean(errors.idOrganisme)}><option value="">Sélectionnez un organisme</option>{organismes.map((item) => <option key={item.idOrganisme} value={item.idOrganisme}>{item.nomOrganisme} ({item.codeOrganisme})</option>)}</select>{field("idOrganisme")}</div><div className="form-field"><label htmlFor="numeroNorme">Numéro de norme <b>*</b></label><input id="numeroNorme" name="numeroNorme" value={form.numeroNorme} onChange={change} aria-invalid={Boolean(errors.numeroNorme)} />{field("numeroNorme")}</div><div className="form-field"><label htmlFor="codeNorme">Code norme <b>*</b></label><input id="codeNorme" name="codeNorme" value={form.codeNorme} onChange={change} aria-invalid={Boolean(errors.codeNorme)} />{field("codeNorme")}</div><div className="form-field"><label htmlFor="nomNorme">Nom de la norme <b>*</b></label><input id="nomNorme" name="nomNorme" value={form.nomNorme} onChange={change} aria-invalid={Boolean(errors.nomNorme)} />{field("nomNorme")}</div><div className="form-field"><label htmlFor="annee">Année</label><input id="annee" name="annee" type="number" min="0" step="1" value={form.annee} onChange={change} aria-invalid={Boolean(errors.annee)} />{field("annee")}</div></div>{errors.form && <p className="form-global-error" role="alert">{errors.form}</p>}{message && <p className="form-success" role="status">{message}</p>}<div className="form-actions"><button type="button" className="reset-button" onClick={reset}><RotateCcw size={18} />Réinitialiser</button><button className="save-button" type="submit" disabled={isSaving}><Save size={18} />{isSaving ? "Enregistrement…" : editingId ? "Modifier" : "Enregistrer"}</button></div></form></article>
    {visible && <article className="units-list-card"><div className="list-card-heading"><div><h2>Liste des normes</h2><p>{loading ? "Chargement…" : `${activeNormes.length} norme(s) disponible(s)`}</p></div></div><div className="units-table-wrap"><table><thead><tr><th>Numéro</th><th>Code</th><th>Norme</th><th>Organisme</th><th>Année</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="6" className="table-state">Chargement des normes…</td></tr> : activeNormes.length ? activeNormes.map((item) => <tr key={item.idNorme}><td>{item.numeroNorme}</td><td>{item.codeNorme}</td><td><strong>{item.nomNorme}</strong></td><td>{organismeName(item.idOrganisme)}</td><td>{item.annee || "—"}</td><td><div className="table-actions"><button className="edit-action" onClick={() => edit(item)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => deactivate(item)}><Trash2 size={16} />Supprimer</button></div></td></tr>) : <tr><td colSpan="6" className="table-state">Aucune norme disponible.</td></tr>}</tbody></table></div></article>}
    {showOrgs && <article className="regions-card"><div className="list-card-heading"><div><h2>Gestion des organismes</h2><p>{organismes.length} organisme(s) disponible(s)</p></div><button className="add-region-button" onClick={() => { resetOrg(); setShowOrgForm(true); }}><Plus size={17} />Ajouter</button></div>{showOrgForm && <form className="region-form" onSubmit={saveOrg} noValidate><div className="form-field"><label htmlFor="codeOrganisme">Code organisme <b>*</b></label><input id="codeOrganisme" name="codeOrganisme" value={orgForm.codeOrganisme} onChange={({ target }) => { setOrgForm((c) => ({ ...c, codeOrganisme: target.value })); setOrgErrors({}); }} aria-invalid={Boolean(orgErrors.codeOrganisme)} />{orgErrors.codeOrganisme && <span className="field-error">{orgErrors.codeOrganisme}</span>}</div><div className="form-field"><label htmlFor="nomOrganisme">Nom de l’organisme <b>*</b></label><input id="nomOrganisme" name="nomOrganisme" value={orgForm.nomOrganisme} onChange={({ target }) => setOrgForm((c) => ({ ...c, nomOrganisme: target.value }))} aria-invalid={Boolean(orgErrors.nomOrganisme)} />{orgErrors.nomOrganisme && <span className="field-error">{orgErrors.nomOrganisme}</span>}</div><div className="form-field"><label htmlFor="imageOrganisme">URL de l’image</label><input id="imageOrganisme" name="imageOrganisme" value={orgForm.imageOrganisme} onChange={({ target }) => setOrgForm((c) => ({ ...c, imageOrganisme: target.value }))} /></div><div className="region-form-actions"><button type="button" className="reset-button" onClick={resetOrg}>Annuler</button><button type="submit" className="save-button" disabled={savingOrg}>{savingOrg ? "Enregistrement…" : editingOrgId ? "Modifier" : "Ajouter"}</button></div></form>}{orgErrors.form && <p className="region-error" role="alert">{orgErrors.form}</p>}<div className="units-table-wrap"><table><thead><tr><th>Code</th><th>Organisme</th><th>Image</th><th>Actions</th></tr></thead><tbody>{organismes.length ? organismes.map((item) => <tr key={item.idOrganisme}><td>{item.codeOrganisme}</td><td><strong>{item.nomOrganisme}</strong></td><td><OrganismeImage src={item.imageOrganisme} alt={`Logo de ${item.nomOrganisme}`} /></td><td><div className="table-actions"><button className="edit-action" onClick={() => editOrg(item)}><Pencil size={16} />Modifier</button><button className="delete-action" onClick={() => deleteOrg(item)}><Trash2 size={16} />Supprimer</button></div></td></tr>) : <tr><td colSpan="4" className="table-state">Aucun organisme disponible.</td></tr>}</tbody></table></div></article>}
  </section>;
}

export default Norme;
